baseURL: "https://www.thesamosborne.com/"
title: thesamosborne
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-185393343-1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: thesamosborne
  description: "Personal Site"
  author: Me

  images: ""

  ShowReadingTime: true
  ShowShareButtons: true
  comments: false
  defaultTheme: dark
  disableThemeToggle: false
  disableSpecial1stPost: false

  assets:
    favicon: "/static/favicon.ico"
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: ">"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Sam Osborne
    imageUrl: "https://i.insider.com/5e506642a9f40c0b63695504?width=1100&format=jpeg&auto=webp"
    imageTitle: profile image
    buttons:
      - name: About
        url: about
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: twitter
      url: "https://twitter.com/thesamosborne"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/samosbor"

  analytics:
    google:
      SiteVerificationTag: "UA-185393343-1"
